### ISSUE TITLE
[FEATURE REQUEST] Restore other VeraCrypt features

### ISSUE THREAD

**Issue by boomam** [dcflachs/docker-containers#11]
Hi,
It would be good if we could get full VeraCrypt functionality within the container.  

There are many functions missing from the menu bar/s that should be there, but are not.
For example, Volumes -> Resume Interrupted Process
I am guessing that this is down to the version of VeraCrypt in use, but regardless, it would be a great feature add to get these back so we can use the container for more than just mounting a given set of containers/devices.

Thanks.

**Comment by dcflachs** [comment]
I have updated the image to contain the latest veracrypt version.
