### ISSUE TITLE
 x11vnc | ssvnc 'ReadExact: Socket error while reading'

### ISSUE THREAD

**Issue by boexler** [dcflachs/docker-containers#2]
I can't connect to the server with encryption enabled. Have you already tried it?

using `Windows 10 64bit` and `SSNVC` ssvnc_windows_only-1.0.30.

I have opened a question on `SuperUser`: https://superuser.com/questions/1310970/x11vnc-ssvnc-readexact-socket-error-while-reading

**Comment by dcflachs** [comment]
Which container in particular are you having problems with? 
Generally speaking I have tried and used all of these containers at one time or another, though only on a linux machine.

**Comment by dcflachs** [comment]
Actually, I see from your link that you are using the veracrypt container. I think you would have more luck asking your question over here  https://github.com/jlesage/docker-baseimage-gui 
The VNC capabilities come from the base image I use, which belongs to jlesage. I have only a basic understanding of how the underlying VNC is implemented.

**Comment by dcflachs** [comment]
@dojo90 Did you get anywhere with this?

**Comment by boexler** [comment]
@dcflachs I have opened an issue 1min ago (https://github.com/jlesage/docker-baseimage-gui/issues/5). I will update this issue here if I have new informations.
