### ISSUE TITLE
Unable to see mounted content in host from container

### ISSUE THREAD

**Issue by boexler** [dcflachs/docker-containers#3]
I'm using this docker image on a `Synology`. I can successfully mount an encrypted container (also from an external usb drive).  In the docker container I can see everything which is in the encrypted container, but I'm not able to see the content of this encryptet container from the host system. It is just empty.
Do you have an idea how to solve this problem? 
I haven't found anything for "shared" folder permission in combination with the synology.

**Comment by dcflachs** [comment]
Make sure that the "/mnt/disks/" host path is mounted with the shared option 
-v </path/to/mount/images>:"/mnt/disks":**shared**
and be sure that you are mounting your container to a subfolder other /mnt/disks

**Comment by boexler** [comment]
I had the following error:
```bash
docker: Error response from daemon: linux mounts: Path /volume3/RAID/Docker/Vera                                                                                                                                                             Crypt/disks is mounted on /volume3/RAID but it is not a shared mount.
```

But after making it shared, everything works as expected!
```bash
root@Tresor001:~# mount --make-rshared /volume3/RAID
```
