### ISSUE TITLE
About 

### ISSUE THREAD

**Issue by alexlongguo** [dcflachs/docker-containers#5]
Hi dcflachs,
I used your project veracrypt-gui:
https://registry.hub.docker.com/r/dcflachs/veracrypt-gui

command:
docker create --name="veracrypt6" --net="bridge" --privileged="true" -e "DISPLAY_WIDTH"="1280" -e "DISPLAY_HEIGHT"="720" -p 5800:5800/tcp -v "/volume2/xxx/in":"/mnt/containers/":rw -v "/volume2/xxx/out":"/mnt/disks":shared dcflachs/veracrypt-gui

Error:
Mount point is already used.

**Comment by dcflachs** [comment]
What OS are you running?

Additionally where does the Error come from? Is it returned by docker or by something within the container (i.e. your seeing it in the container logs)?

**Comment by alexlongguo** [comment]
Thank you for your replied.
Same problem as :
https://github.com/veracrypt/VeraCrypt/issues/464

OS：Synology NAS
Error info come from web gui，here is my steps:

About images:
#docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
dcflachs/veracrypt-gui            latest              b914d0ffddf6        5 weeks ago         235MB
dcflachs/veracrypt-gui            experimental        944cfb280919        5 weeks ago         258MB


Here you can see /volume2 info,shared
#cat /proc/1/mountinfo 
16 1 9:0 / / rw,relatime - ext4 /dev/md0 rw,journal_checksum,barrier,data=ordered
14 16 0:5 / /dev rw,nosuid,noexec,relatime - devtmpfs none rw,size=506220k,nr_inodes=126555,mode=755
15 14 0:11 / /dev/pts rw,nosuid,noexec,relatime - devpts none rw,gid=5,mode=620,ptmxmode=000
17 16 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc none rw
19 16 0:13 / /sys rw,nosuid,nodev,noexec,relatime - sysfs none rw
20 16 0:15 / /tmp rw,relatime - tmpfs /tmp rw
21 16 0:16 / /run rw,nosuid,nodev,relatime - tmpfs /run rw,mode=755
22 14 0:17 / /dev/shm rw,nosuid,nodev,relatime - tmpfs /dev/shm rw
23 19 0:18 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
24 21 0:19 / /run/cgmanager/fs rw,relatime - tmpfs cgmfs rw,size=100k,mode=755
27 23 0:23 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset,release_agent=/run/cgmanager/agents/cgm-release-agent.cpuset,clone_children
28 23 0:21 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu,release_agent=/run/cgmanager/agents/cgm-release-agent.cpu
29 23 0:22 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct,release_agent=/run/cgmanager/agents/cgm-release-agent.cpuacct
31 23 0:26 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory,release_agent=/run/cgmanager/agents/cgm-release-agent.memory
32 23 0:24 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices,release_agent=/run/cgmanager/agents/cgm-release-agent.devices
33 23 0:25 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer,release_agent=/run/cgmanager/agents/cgm-release-agent.freezer
34 23 0:20 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio,release_agent=/run/cgmanager/agents/cgm-release-agent.blkio
45 17 0:5 /bus/usb /proc/bus/usb rw,nosuid,noexec,relatime - devtmpfs none rw,size=506220k,nr_inodes=126555,mode=755
46 19 0:7 / /sys/kernel/debug rw,relatime - debugfs none rw
47 19 0:10 / /sys/kernel/security rw,relatime - securityfs securityfs rw
48 16 0:28 / /volume3 rw,relatime shared:5 - btrfs /dev/md4 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50
49 16 0:32 / /volume1 rw,relatime shared:2 - btrfs /dev/md2 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50
50 16 0:33 / /volume2 rw,relatime shared:3 - btrfs /dev/md3 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50
51 16 0:14 / /config rw,relatime - configfs none rw
52 17 0:75 / /proc/fs/nfsd rw,relatime - nfsd none rw
53 16 0:32 /@optware /opt rw,relatime - btrfs /dev/md2 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50
54 49 0:32 /@docker /volume1/@docker rw,relatime shared:1 - btrfs /dev/md2 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50
55 54 0:32 /@docker/btrfs /volume1/@docker/btrfs rw,relatime shared:1 - btrfs /dev/md2 rw,synoacl,nospace_cache,flushoncommit_threshold=1000,metadata_ratio=50


create docker container and start it:
#docker create --name="veracrypt1" --net="bridge" --privileged="true" -e "DISPLAY_WIDTH"="1280" -e "DISPLAY_HEIGHT"="720" -p 5800:5800/tcp -v "/volume2/xxx/in/":"/mnt/containers/":rw -v "/volume2/xxx/out/":"/mnt/disks":shared dcflachs/veracrypt-gui
c7c0c9b5aa4531f6beb0d486c27f7e1514f11c9a886523edf832a6e601074e4e
#docker ps -a
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
c7c0c9b5aa45        dcflachs/veracrypt-gui   "/init"             21 seconds ago      Created                                 veracrypt1
sh-4.3#docker start veracrypt1
veracrypt1
sh-4.3#docker exec -it veracrypt1 /bin/bash
root@c7c0c9b5aa45:/tmp# 


Open Web GUI:
![image](https://user-images.githubusercontent.com/17021671/83991432-4b732700-a97f-11ea-8951-a67794da63b6.png)
![image](https://user-images.githubusercontent.com/17021671/83989800-2b8d3480-a97a-11ea-9692-827be659c095.png)

**Comment by dcflachs** [comment]
@alexlongguo  I will take a closer look at this tomorrow but my first two thoughts are as follows. First make sure you are using the dcflachs/veracrypt-gui latest image not the experimental tag. Second dont use the /mnt/disks directory as your mount point in Veracrypt. You should mount to a sub-directory of /mnt/disks e.g. /mnt/disks/disk1

**Comment by alexlongguo** [comment]
`Second dont use the /mnt/disks directory as your mount point in Veracrypt. You should mount to a sub-directory of /mnt/disks e.g. /mnt/disks/disk1`
It's worked,thank you soooooooooooooo much!
It took me many days to solve this problem and made no progress, but you solved it as soon as you did it. You are so awesome.

**Comment by dcflachs** [comment]
Glad to help.
